import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import Navbar from '../components/Navbar'
import { NewComponentContext, NewComponentProvider } from '../Context/NewComponentContext'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Navbar />
      <Login />
     

    </div>
  )
}

export default Home
